name: somu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.6
  flutter_svg: ^1.0.3
  flutter_inappwebview: ^5.4.3+7
  sliver_tools: ^0.2.7
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/Staffordshire_Police_full.png
    - assets/MobilePhones.svg
    - assets/Computers.svg
    - assets/Tablets.svg
    - assets/GameConsoles.svg
    - assets/AppleLogo.svg
    - assets/Android.svg
    - assets/test_photo.png
    - assets/book.png
    - assets/calls/homepage.jpeg
    - assets/calls/app_drawer.jpeg
    - assets/calls/call_log.jpg
    - assets/messages/messages_app.jpeg
    - assets/messages/archive_messages.jpeg
    - assets/gallery/archive_photos.jpeg
    - assets/gallery/photos.jpeg
    - assets/downloads/open_drawer.jpeg
    - assets/downloads/download_button.jpeg
    - assets/downloads/open_downloads_ios.jpg
    - assets/downloads/step_2_ios.jpg
    - assets/downloads/step_3_ios.jpg
    - assets/downloads/step_4_ios.jpg
    - assets/snapchat/homescreen.jpg
    - assets/snapchat/mysnaps.jpg
    - assets/snapchat/my_eyes_only.jpg
    - assets/whatsapp/chat_screen.jpg
    - assets/whatsapp/archived_chats.png
    - assets/chrome/step1.webp
    - assets/chrome/step2.webp
    - assets/chrome/step_1_ios.jpg
    - assets/chrome/step_2_ios.jpg
    - assets/chrome/step_3_ios.jpg
    - assets/calls/ios_homepage.jpg
    - assets/calls/ios_recent_calls.jpg
    - assets/calls/ios_calls_info.jpg
    - assets/snapchat/open_snapchat_ios.jpg
    - assets/whatsapp/open_whatsapp_ios.jpg
    - assets/gallery/open_gallery_ios.jpg
    - assets/gallery/search_photos_ios.jpg
    - assets/gallery/hidden_archived_photos_ios.jpg
    - assets/google_activity/step_1.jpg
    - assets/google_activity/step_2.jpg
    - assets/google_activity/step_3.jpg
    - assets/google_activity/step_4.jpg
    - assets/seize_device/step_1_ios.jpeg
    - assets/seize_device/step_2_ios.jpg
    - assets/seize_device/step_3_ios.jpg
    - assets/seize_device/step_4_ios.jpg
    - assets/seize_device/step_5_ios.jpg
    - assets/seize_device/step_6_ios.jpg
    - assets/seize_device/step_7_ios.jpg
    - assets/seize_device/step_8_ios.jpg
    - assets/seize_device/step_1_android.jpeg
    - assets/seize_device/step_2_android.jpg
    - assets/seize_device/step_3_android.jpg
    - assets/seize_device/step_4_android.jpg
    - assets/seize_device/step_5_android.jpg
    - assets/seize_device/step_6_android.jpg
    - assets/hidden_apps/step_1_ios.jpg
    - assets/hidden_apps/step_2_ios.png
    - assets/hidden_apps/step_3_ios.png
    - assets/hidden_apps/step_1_android.jpg
    - assets/hidden_apps/step_2_android.jpg
    - assets/hidden_apps/step_3_android.jpg
    - assets/messages/homepage_ios.jpg
    - assets/messages/messages_ios.jpg
    - assets/remove_phone_case.webp
    - assets/back_side_phone.jpg
    - assets/iOS_android_logos.jpeg

  fonts:
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/book.png"

flutter_native_splash:
  image: "assets/Staffordshire_Police_full.png"
  color: "#FFFFFF"
  android: true